# Generated by Django 2.1.7 on 2020-01-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang',
            new_name='name',
        ),
    ]
